import Head from 'next/head'
//import Image from 'next/image'
//import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import { CoordCard, SubCoordCard, DeptCard, EventCard, Footer, Header } from '@/components'
import { members } from '../members'
import { eventsArr } from '../events'

//const inter = Inter({ subsets: ['latin'] })
//Unused font

export default function Home() {
	return (
		<>
			<Head>
				<title>NJACK</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header selected={'Home'} />
			<div className={styles.parentDiv}>
				<div className={styles.heroSection}>
					<img loading='lazy' src='/home/NJACK logo.svg' alt='NJACK Logo' />
					<div className={styles.heroText}>NJACK</div>
					<div className={styles.subHeroText}>Not just another Computer Science Klub</div>
				</div>
				<div className={styles.aboutSection}>
					<h2>About us</h2>
					<p>
						NJACK is the esteemed Computer Science Club at IIT Patna, dedicated to fostering a community of passionate computer science enthusiasts. With its wide range of departments and initiatives, NJACK aims to provide a platform for students to enhance their skills, engage in productive sessions, and participate in fun events.
						As a collective entity, NJACK serves as a nurturing platform for students passionate about computer science at IIT Patna. It provides a vibrant community where like-minded individuals can come together to share knowledge, collaborate on projects, and stay updated with the latest advancements in the field. NJACK organizes guest lectures, coding competitions, hackathons, and other events to foster learning and networking opportunities for its members. Through its inclusive and supportive environment, NJACK strives to empower students, enabling them to excel in their computer science journey and make meaningful contributions to the world of technology.
					</p>
				</div>
				<div className={styles.section} style={{ backgroundColor: '#F1F1F1' }}>
					<h2 className={styles.sectionHeading}>Upcoming Events</h2>
					<div className={styles.cardSection}>
						{/* TODO: Add the event cards as a components */}
						{eventsArr.map((event) => {
							return event.old==false?<EventCard key={event.key} old={event.old} eventName={event.eventName} desc={event.desc} image={event.image} registerLink={event.registerLink} />:null
						})}
					</div>
				</div>
				<div className={styles.section}>
					<h2 className={styles.sectionHeading}>Our Departments</h2>
					<div className={styles.cardSection}>
						{/* TODO: Add the department cards as a components */}
						<DeptCard
							deptName={'Competitive Programming'}
							deptImage={'/home/heroImage.png'}
							deptDesc={
								"The Competitive Programming Department at NJACK is committed to honing students' problem-solving skills, algorithmic thinking, and programming prowess. Through regular coding contests, workshops, and practice sessions, this department helps participants develop their abilities to solve complex programming challenges efficiently."
							}
							deptLink={'/departments/cp'}
							bgColor={'#FF6559'}
						/>
						<DeptCard
							deptName={'Dev and OS'}
							deptImage={'/home/heroImage.png'}
							deptDesc={
								"The Development and Open Source Department at NJACK encourages students to delve into the world of software development and contribute to the open-source community. Through hands-on workshops, collaborative projects, and mentorship programs, this department nurtures students' skills in building robust and scalable software solutions. "
							}
							deptLink={'/departments/devos'}
							bgColor={'#0091BD'}
						/>
						<DeptCard
							deptName={'Machine Learning'}
							deptImage={'/home/heroImage.png'}
							deptDesc={
								"The Machine Learning Department of NJACK is dedicated to exploring the vast field of artificial intelligence and machine learning. Through workshops, lectures, and practical sessions, this department equips members with the knowledge and tools required to tackle complex problems using machine learning algorithms."
							}
							deptLink={'/departments/ml'}
							bgColor={'#FFAC2A'}
						/>
						<DeptCard
							deptName={'Cyber Securities'}
							deptImage={'/home/heroImage.png'}
							deptDesc={
								"The Cybersecurity Department at NJACK focuses on promoting awareness and understanding of the crucial field of cybersecurity. This department conducts workshops, seminars, and hands-on sessions to educate members about various cybersecurity threats, techniques, and countermeasures."
							}
							deptLink={'/departments/cybersec'}
							bgColor={'#6EEDF3'}
						/>
					</div>
				</div>
				<div className={styles.section}>
					<h2 className={styles.sectionHeading}>Our Team</h2>
					<h3>Coordinators</h3>
					<div className={styles.cardSection}>
						{/* TODO: Add the coordinator cards as a components */}
						{members[0].map((member) => {
							if (member.committee === 'Overall Coordinator') {
								return <CoordCard coordName={member.name} coordImage={"https://drive.google.com/uc?export=view&id="+member.image} coordCommitee={member.committee} coordLinkedIn={member.linkedin} coordGitHub={member.github} />
							}
						})}
					</div>
					<div className={styles.cardSection}>
						{members[0].map((member) => {
							if (member.committee !== 'Overall Coordinator') {
								return <CoordCard coordName={member.name} coordImage={"https://drive.google.com/uc?export=view&id="+member.image} coordCommitee={member.committee} coordLinkedIn={member.linkedin} coordGitHub={member.github} />
							}
						})}
					</div>
					<h3>Sub-Coordinators</h3>
					<div className={styles.cardSection}>
						{/* TODO: Add the team cards as a components */}
						<div className={styles.committee}>
							<p>Competitive Programming</p>
							{members[1].map((member) => {
							if(member.committee === 'CP'){
							return (<SubCoordCard coordName={member.name} coordLinkedIn={member.linkedin}></SubCoordCard>)
							}})}
						</div>
						<div className={styles.committee}>
							<p>Development & Open Source</p>
							{members[1].map((member) => {
							if(member.committee === 'Dev&OS'){
							return (<SubCoordCard coordName={member.name} coordLinkedIn={member.linkedin}></SubCoordCard>)
							}})}
						</div>
						<div className={styles.committee}>
							<p>Machine Learning</p>
							{members[1].map((member) => {
							if(member.committee === 'ML'){
							return (<SubCoordCard coordName={member.name} coordLinkedIn={member.linkedin}></SubCoordCard>)
							}})}
						</div>
						<div className={styles.committee}>
							<p>Cyber Securities</p>
							{members[1].map((member) => {
							if(member.committee === 'CyberSec'){
							return (<SubCoordCard coordName={member.name} coordLinkedIn={member.linkedin}></SubCoordCard>)
							}})}
						</div>
					</div>
				</div>
				<img
					alt='TeamWork'
					src='\home\team.png'
					style={{
						alignSelf: 'end',
						marginInline: '5%',
						maxWidth: '90vw',
						maxHeight: '25vh',
						objectFit: 'contain',
					}}
				/>
				<Footer />
			</div>
		</>
	)
}
